apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssbackend-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssbackendapp
  template:
    metadata:
      labels:
        app: ssbackendapp
    spec:
      containers:
      - name: ssbackendcontainer
        image: dixit7/hotstar:v1
        resources:
          requests:
            memory: "150Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: ssbackendsvc
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: ssbackendapp
  ports:
  - port: 8000
    targetPort: 3000

